# This is a basic workflow to help you get started with Actions

name: clone

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /pub/${{secrets.USERNAME}}
            git clone https://github.com/RushilSavalia01/personal-website.git
